apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  labels:
    {{- include "service-chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    {{- range .Values.ports }}
    - port: {{ .port }}
      targetPort: {{ .port }}
      protocol: TCP
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "service-chart.selectorLabels" . | nindent 4 }}
