name: Services Workflow
on: 
  push:
    branches:
      - master
  workflow_dispatch:
    
jobs:
  payment-service-workflow:
    name: Payment Service Workflow
    uses: ./.github/workflows/service_workflow_base.yml
    with:
      service-name: 'payment-service'
      project-name: 'PaymentService'
    secrets: inherit

  rental-service-workflow:
    name: Rental Service Workflow
    uses: ./.github/workflows/service_workflow_base.yml
    with:
      service-name: 'rental-service'
      project-name: 'RentalService'
    secrets: inherit

  cars-service-workflow:
    name: Cars Service Workflow
    uses: ./.github/workflows/service_workflow_base.yml
    with:
      service-name: 'cars-service'
      project-name: 'CarsService'
    secrets: inherit

  api-gateway-workflow:
    name: API Gateway Workflow
    uses: ./.github/workflows/service_workflow_base.yml
    with:
      service-name: 'api-gateway'
      project-name: 'GatewayService'
    secrets: inherit

  deploy: 
    name: Deploy
    needs: [ payment-service-workflow, rental-service-workflow, cars-service-workflow, api-gateway-workflow ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      #- name: Send docker-compose
      #  uses: appleboy/scp-action@v0.1.4
      #  with:
      #    host: ${{ secrets.DEPLOY_HOST }}
      #    username: ${{ secrets.DEPLOY_USERNAME }}
      #    password: ${{ secrets.DEPLOY_PASSWORD }}
      #    port: ${{ secrets.DEPLOY_PORT }}
      #    source: docker-compose.yml
      #    target: rsoi/

      #- name: Deploy
      #  uses: appleboy/ssh-action@v1.0.0
      #  with:
      #    host: ${{ secrets.DEPLOY_HOST }}
      #    username: ${{ secrets.DEPLOY_USERNAME }}
      #    password: ${{ secrets.DEPLOY_PASSWORD }}
      #    port: ${{ secrets.DEPLOY_PORT }}
      #    script: |
      #      docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      #      docker-compose -f rsoi/docker-compose.yml down
      #      docker-compose -f rsoi/docker-compose.yml pull
      #      docker-compose -f rsoi/docker-compose.yml up -d

  autograding-workflow:
    name: Autograding workflow
    needs: [ deploy ]
    uses: ./.github/workflows/classroom.yml
    secrets: inherit